#### Question 4 -
Write a program to download the data from the link given below and then read the data and convert the into
the proper structure and return it as a CSV file.

Link - https://data.nasa.gov/resource/y77d-th95.json

Note - Write code comments wherever needed for code understanding.



Excepted Output Data Attributes
● Name of Earth Meteorite - string id - ID of Earth

● Meteorite - int nametype - string recclass - string

● mass - Mass of Earth Meteorite - float year - Year at which Earth

● Meteorite was hit - datetime format reclat - float recclong - float

● point coordinates - list of int

In [1]:
import requests
import pandas as pd

URL = "https://data.nasa.gov/resource/y77d-th95.json"


def download_data(url):
    try:
        # Download the data using requests.get from the given URL
        response = requests.get(url)
        return response.json()
    except requests.ConnectionError as e:
        print("Connection error, please try again later...")
        return None
    except requests.Timeout as e:
        print("Connection timeout error, please try again later...")
        return None


def convert_to_dataframe(data):
    if data is None:
        return None
    else:
        # Convert the data into a pandas dataframe
        df = pd.json_normalize(data)
        return df


def save_to_csv(df, filename):
    if df is not None:
        # Saving the dataframe to a CSV file
        df.to_csv(filename, index=False)
        print("File created successfully.")
    else:
        print("Unable to save the file. DataFrame is empty.")


def read_from_csv(filename):
    try:
        # Read the data from the CSV file
        df_read = pd.read_csv(filename)
        return df_read
    except FileNotFoundError as e:
        print("File not found. Please check the filename or path.")
        return None

In [2]:
# Download the data
nasa_data = download_data(URL)

# Convert the data to a DataFrame
nasa_df = convert_to_dataframe(nasa_data)

# Print the first few rows of the DataFrame
print(nasa_df.head())

# Save the DataFrame to a CSV file
save_to_csv(nasa_df, "nasa_output.csv")

# Read the data from the CSV file to verify
df_read = read_from_csv("nasa_output.csv")
print(df_read.head())

       name   id nametype     recclass    mass  fall                     year
0    Aachen    1    Valid           L5      21  Fell  1880-01-01T00:00:00.000  \
1    Aarhus    2    Valid           H6     720  Fell  1951-01-01T00:00:00.000
2      Abee    6    Valid          EH4  107000  Fell  1952-01-01T00:00:00.000
3  Acapulco   10    Valid  Acapulcoite    1914  Fell  1976-01-01T00:00:00.000
4   Achiras  370    Valid           L6     780  Fell  1902-01-01T00:00:00.000

       reclat      reclong geolocation.type geolocation.coordinates
0   50.775000     6.083330            Point       [6.08333, 50.775]  \
1   56.183330    10.233330            Point    [10.23333, 56.18333]
2   54.216670  -113.000000            Point        [-113, 54.21667]
3   16.883330   -99.900000            Point       [-99.9, 16.88333]
4  -33.166670   -64.950000            Point     [-64.95, -33.16667]

  :@computed_region_cbhk_fwbd :@computed_region_nnqa_25f4
0                         NaN                         NaN
1                         NaN                         NaN
2                         NaN                         NaN
3                         NaN                         NaN
4                         NaN                         NaN
File created successfully.
       name   id nametype     recclass      mass  fall
0    Aachen    1    Valid           L5      21.0  Fell  \
1    Aarhus    2    Valid           H6     720.0  Fell
2      Abee    6    Valid          EH4  107000.0  Fell
3  Acapulco   10    Valid  Acapulcoite    1914.0  Fell
4   Achiras  370    Valid           L6     780.0  Fell

                      year    reclat    reclong geolocation.type
0  1880-01-01T00:00:00.000  50.77500    6.08333            Point  \
1  1951-01-01T00:00:00.000  56.18333   10.23333            Point
2  1952-01-01T00:00:00.000  54.21667 -113.00000            Point
3  1976-01-01T00:00:00.000  16.88333  -99.90000            Point
4  1902-01-01T00:00:00.000 -33.16667  -64.95000            Point

  geolocation.coordinates  :@computed_region_cbhk_fwbd
0       [6.08333, 50.775]                          NaN  \
1    [10.23333, 56.18333]                          NaN
2        [-113, 54.21667]                          NaN
3       [-99.9, 16.88333]                          NaN
4     [-64.95, -33.16667]                          NaN

   :@computed_region_nnqa_25f4
0                          NaN
1                          NaN
2                          NaN
3                          NaN
4                          NaN